# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gou', '0002_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('user', 'item')]),
        ),
    ]
