# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-07 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gou', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemInts', to='gou.Item', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemInts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'item_int',
                'verbose_name': 'itemInts',
                'verbose_name_plural': 'itemInts',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'man'), (0, 'woman')], verbose_name='gender'),
        ),
    ]
